### ISSUE TITLE
Commands are not executed after successful authentication due to false verification of the login response

### ISSUE THREAD

**Issue by matthias-huber** [Appdynamics/api-commandline-tool#12]
The if statement  
`if [[ "${LOGIN_RESPONSE/200 OK}" != "${LOGIN_RESPONSE}" ]]; then`
does not work as intended for the response with content `HTTP/2 200`

Skript execution fails with the error message: "Controller Login Error! Please check hostname and credentials"

Alternatives:
- check only for 200 if this clearly indicates that the authentication was successful
- verify other content. Maybe the existence of a JSESSIONID?

**Comment by svrnm** [comment]
Thanks for reporting that issue. I have to look into it! Checking for 200 might be to simple, but I check the option with JSESSIONID or adding a second option for http2.

**Comment by svrnm** [comment]
@matthias-huber please verify if the latest commit fixes your issue.

**Comment by matthias-huber** [comment]
@svrnm Thanks. It works now with the newest version of the shell script
