### ISSUE TITLE
HTTP 500 on ./act.sh licenserule list

### ISSUE THREAD

**Issue by jeromeguillaume** [Appdynamics/api-commandline-tool#19]
Hello,

I have systematically a HTTP 500 error when I call /act.sh licenserule list.

I use the latest release of act (date: 13 February 2020)
The Controller version is  4.5.16.2261

<img width="906" alt="Capture d’écran 2020-02-13 à 17 33 41" src="https://user-images.githubusercontent.com/4004310/74456725-8ceb3e00-4e87-11ea-9981-a4b27d1609ce.png">

**Comment by svrnm** [comment]
is this still relevant @jeromeguillaume ?

**Comment by jeromeguillaume** [comment]
Right now: no.

Maybe, next time. So, if you have higher priorities you can close this thicket.

Thanks Severin
________________________________
De : Severin Neumann <notifications@github.com>
Envoyé : lundi 29 juin 2020 17:41
À : Appdynamics/api-commandline-tool <api-commandline-tool@noreply.github.com>
Cc : jeromeguillaume <jerome.guillaume@live.fr>; Mention <mention@noreply.github.com>
Objet : Re: [Appdynamics/api-commandline-tool] HTTP 500 on ./act.sh licenserule list (#19)


is this still relevant @jeromeguillaume<https://github.com/jeromeguillaume> ?
