### ISSUE TITLE
No consistent values are retrieved on act.sh controller call

### ISSUE THREAD

**Issue by jeromeguillaume** [Appdynamics/api-commandline-tool#20]
Hello,

When I call `act.sh controller call /controller/restui/user/account` no values are retrieved (like accessKey)

Controller Version is 4.5.16
 
<img width="1023" alt="Capture d’écran 2020-02-13 à 17 38 51" src="https://user-images.githubusercontent.com/4004310/74457039-04b96880-4e88-11ea-844e-49b639dfb451.png">

**Comment by svrnm** [comment]
@jeromeguillaume this might be on purpose, can you get the accessKey if you run the same query on the UI, what have you been looking for exactly, maybe I can figure out the right call.

**Comment by svrnm** [comment]
@jeromeguillaume had you have the chance to look into that thing with the accessKey I mentioned above?

**Comment by svrnm** [comment]
Closing this issue now, please open another one of you have any further questions.
