### ISSUE TITLE
There is no update for the sub-command dbmon

### ISSUE THREAD

**Issue by gyang2300** [Appdynamics/api-commandline-tool#21]
The USAGE file says:
Use the Database Visibility API to get, create, update, and delete Database Visibility Collectors.

However, there is no update sub-command. I've added the following two lines to act.sh to add the missing sub-command:

dbmon_update() { apiCall -X POST -d '{{d:database_collector_definition}}' '/controller/rest/databases/collectors/update' "$@" ; }
rde dbmon_update "Update a collector." "Provide a json string or a @file (-d) as parameter." "-d @collector.json"

**Comment by svrnm** [comment]
Thanks! I added that command
