### ISSUE TITLE
How to export and import applications between controllers ?

### ISSUE THREAD

**Issue by nanjum88** [Appdynamics/api-commandline-tool#22]
Going through this amazing tool with several options. 

We're migrating to a new controller machine and wanted to explore options on how to export and import applications between the controllers ?

We want to atleast start with exporting list of applications from controller A and then import the list of applications in Controller B. 

Any insights will help, while I keep exploring the tool more. 
Thanks

**Comment by svrnm** [comment]
Hi @nanjum88,

while ACT can help you to move configurations from one controller to another it's not designed for full migrations. 

Are you an AppD employee or a customer? In the first case, ping me internally so I can point you to the right way of doing it. In the second case, you should get in touch with your AppDynamics representative or our support team to ask for help in that matter.
