### ISSUE TITLE
Trying to connect my saas instance - Getting credentials error.

### ISSUE THREAD

**Issue by asafkiv** [Appdynamics/api-commandline-tool#25]
./act.sh dashboard list                                                                                                  
grep: **/home/mobaxterm/.appdynamics/act/cookie.txt: No such file or directory
Controller Login Error! Please check hostname and credentials**

This command with same credentials works ok:
curl  -k --basic --user user@account:password                                                                https://myinstancename.saas.appdynamics.com/controller/rest/applications?output-J  
Any Ideas how to fix this?

**Comment by svrnm** [comment]
Can you check if the folder /home/mobaxterm/.appdynamics exists and also the act subfolder? Also, run

`./act.sh -vvv dashboard list`

to get some debug info that might help.

**Comment by asafkiv** [comment]
Thanks. 
Location exists, here is the output:
DEBUG: CONFIG_CONTROLLER_HOST=https://instancename.saas.appdynamics.com
DEBUG: CONFIG_CONTROLLER_CREDENTIALS=instancename@instancename:password
DEBUG: CONFIG_CONTROLLER_COOKIE_LOCATION=/home/mobaxterm/api-commandline-tool-master/cookie.txt
DEBUG: CONFIG_OUTPUT_VERBOSITY=error,output,warn,info,debug
DEBUG: CONFIG_USER_PLUGIN_DIRECTORY=/home/mobaxterm/.appdynamics/act/plugins
DEBUG: dashboard has commands
DEBUG: dashboard_list is a valid command
DEBUG: Unparsed endpoint is /controller/restui/dashboards/getAllDashboardsByType/false
DEBUG: Unparsed payload is
DEBUG: Identified Options:
DEBUG: Identified Types:
DEBUG: Optional Options:
DEBUG: With form: 0
DEBUG: Call Controller with -d  -X GET /controller/restui/dashboards/getAllDashboardsByType/false
DEBUG: Calling https://instancename.saas.appdynamics.com
DEBUG: -d  -X GET /controller/restui/dashboards/getAllDashboardsByType/false
DEBUG: Login at https://instancename.saas.appdynamics.com with instancename@instancename:password
DEBUG: RESPONSE: DEBUG: curl -L --connect-timeout 10 -sI -c /home/mobaxterm/api-commandline-tool-master/cookie.txt --user instancename@instancename:password https://instancename.saas.appdynamics.com/controller/auth?action=login
grep: /home/mobaxterm/api-commandline-tool-master/cookie.txt: No such file or directory
DEBUG: XCSRFTOKEN:
DEBUG: Login result: Controller Login Error! Please check hostname and credentials
Controller Login Error! Please check hostname and credentials
DEBUG: END

**Comment by svrnm** [comment]
Can you check the file /home/mobaxterm/.appdynamics/act/config.sh and see what CONFIG_CONTROLLER_COOKIE_LOCATION is there or do you have modified that on purpose? 
Also, make sure that the following gives you a successful login:

`./act.sh -vvv controller login`

**Comment by asafkiv** [comment]
I have changed the path in the config file manually. 
no luck with the login command:
[Asaf.Kivity-i7] ➤ ./act.sh -vvv controller login
DEBUG: CONFIG_CONTROLLER_HOST=https://instancename.saas.appdynamics.com
DEBUG: CONFIG_CONTROLLER_CREDENTIALS=instancename@instancename:password
DEBUG: CONFIG_CONTROLLER_COOKIE_LOCATION=/home/mobaxterm/api-commandline-tool-master/cookie.txt
DEBUG: CONFIG_OUTPUT_VERBOSITY=error,output,warn,info,debug
DEBUG: CONFIG_USER_PLUGIN_DIRECTORY=/home/mobaxterm/.appdynamics/act/plugins
DEBUG: controller has commands
DEBUG: controller_login is a valid command
DEBUG: Login at https://instancename.saas.appdynamics.com with instancename@instancename:password
DEBUG: RESPONSE: DEBUG: curl -L --connect-timeout 10 -sI -c /home/mobaxterm/api-commandline-tool-master/cookie.txt --user instancename@instancename:password https://instancename.saas.appdynamics.com/controller/auth?action=login
grep: /home/mobaxterm/api-commandline-tool-master/cookie.txt: No such file or directory
DEBUG: XCSRFTOKEN:
Controller Login Error! Please check hostname and credentials
DEBUG: END

[2020-06-29 19:26.54]  ~/api-commandline-tool-master
[Asaf.Kivity-i7] ➤ ls -ltr
total 161
-rwxr-xr-x    1 Asaf     UsersGrp      6938 May 28 18:02 ysh
-rwxr-xr-x    1 Asaf     UsersGrp      4301 May 28 18:02 yaml-build.sh
-rw-r--r--    1 Asaf     UsersGrp     90076 May 28 18:02 postman-collection.json
-rwxr-xr-x    1 Asaf     UsersGrp      7712 May 28 18:02 main.sh
-rw-r--r--    1 Asaf     UsersGrp     33833 May 28 18:02 commands.yml
-rwxr-xr-x    1 Asaf     UsersGrp       602 May 28 18:02 build.sh
-rwxr-xr-x    1 Asaf     UsersGrp     86154 May 28 18:02 act.sh
-rw-r--r--    1 Asaf     UsersGrp     26384 May 28 18:02 USAGE.md
-rw-r--r--    1 Asaf     UsersGrp      3742 May 28 18:02 RECIPES.md
-rw-r--r--    1 Asaf     UsersGrp      5498 May 28 18:02 README.md
-rw-r--r--    1 Asaf     UsersGrp      4044 May 28 18:02 POSTMAN.md
-rw-r--r--    1 Asaf     UsersGrp     11358 May 28 18:02 LICENSE
drwxr-xr-x    1 Asaf     UsersGrp         0 Jun 29 17:36 tests
drwxr-xr-x    1 Asaf     UsersGrp         0 Jun 29 17:36 recipes
drwxr-xr-x    1 Asaf     UsersGrp         0 Jun 29 17:36 helpers
drwxr-xr-x    1 Asaf     UsersGrp         0 Jun 29 17:36 examples
drwxr-xr-x    1 Asaf     UsersGrp         0 Jun 29 17:36 commands
-rwxr-xr-x    1 Asaf     UsersGrp      8220 Jun 29 18:00 test.sh

[2020-06-29 19:27.00]  ~/api-commandline-tool-master

**Comment by asafkiv** [comment]
its somehow related to mobaxterm. from a linux terminal it works fine. Thanks a lot for your help!
