### ISSUE TITLE
Disable Agent action prompts for password and fails searching for non-existent file appdynamics-controller-cookie.txt

### ISSUE THREAD

**Issue by nanjum88** [Appdynamics/api-commandline-tool#26]
I setup the controller profile and ran certain actions, which worked fine (example list agent ids, applications, create applications) , but when I try to disable agents, I get the following prompt 

/opt/appd-utils/act.sh agents disable -i 469397
Enter host password for user '':
grep: /tmp/appdynamics-controller-cookie.txt: No such file or directory

profile info
/root/.appdynamics/act

cat config.saas-nonprod.sh
CONFIG_CONTROLLER_HOST=https://*******.saas.appdynamics.com
CONFIG_CONTROLLER_CREDENTIALS=*****-****@*****:*****
CONFIG_CONTROLLER_COOKIE_LOCATION=/root/.appdynamics/act/cookie.txt
CONFIG_USER_PLUGIN_DIRECTORY=/root/.appdynamics/act/plugins
CONFIG_PORTAL_CREDENTIALS=

For security reasons, masked controller information and credentials

**Comment by nanjum88** [comment]
any updates/insights @svrnm ?

Appreciate your help.

**Comment by svrnm** [comment]
@nanjum88 can you run that command with -vvv again to get some debug output?

**Comment by svrnm** [comment]
Also, are you running act.sh as root or as another user?

**Comment by nanjum88** [comment]
hi @svrnm , 
I was able to resolve the issue this morning; was actually making a mistake. I have multiple controllers and I forgot to specify the controller in the disable command, which I corrected and got it working. 

./act.sh -vvv -E saas-nonprod agents disable -i 277394 -m true 

However, I see there's no command to enable the agents back; also there's no command to disable individual machineagents.

**Comment by svrnm** [comment]
> However, I see there's no command to enable the agents back; also there's no command to disable individual machineagents.

That's right, let me see if I can add them somehow easily.

**Comment by svrnm** [comment]
have a look into the last commit, there are now additional commands for enabling agents back and enable/disable for machine agents.

**Comment by nanjum88** [comment]
hi @svrnm  - 

Thank you. I tried the new build.  but doesn't work for Machine agents. 
The machine with machineID exists but still returns "Could not find machine id: 277438"

/opt/appd-utils/act.sh -E saas-nonprod agents toggleMachineAgent -i 277438 -m false
{
  "displayText" : "Could not find machine id: 277438",
  "messageKey" : null,
  "localizationBundle" : null,
  "showWithNotificationService" : true,
  "rootExceptionClass" : "",
  "notErrorMessage" : false,
  "unauthorizedAccess" : false,
  "noDataFound" : false
}

Snapshot - 

![image](https://user-images.githubusercontent.com/32209105/87746285-083d7c80-c7a5-11ea-954c-a44d16ded278.png)

**Comment by nanjum88** [comment]
@svrnm  - any updates ? 

Thank you

**Comment by svrnm** [comment]
@nanjum88  sorry, I missed your last comment. The machine id you have to use comes from this list:

/controller/#/location=SETTINGS_MACHINE_AGENTS&timeRange=last_1_hour.BEFORE_NOW.-1.-1.60

You have to look into the AJAX calls when you enable/disable an agent and copy the ID out.

Hope that helps

**Comment by svrnm** [comment]
Closing this issue now, please open another one of you have any further questions.
