### ISSUE TITLE
Is there a way to delete Service Endpoints using the API

### ISSUE THREAD

**Issue by nanjum88** [Appdynamics/api-commandline-tool#31]
We're trying to clean-up service endpoints that are detected by default service endpoints detection rules, but the UI for service endpoint doesn't allow group selection or select more than one service endpoint at a time to delete them. 

Checking if we've a method to bulk delete the SEPs by passing the id's or delete all existing SEPs for an application?

**Comment by svrnm** [comment]
What version of the controller are you using? The newly designed UI for the SEPs does allow selecting multiple and deleting multiple endpoints.

For sure I can add a feature for deleting SEPs, but depending on your controller version there might be differences on how the APIs work.

**Comment by nanjum88** [comment]
Hi @svrnm , 

I figured out the way to select multiple SEPs from the controller UI and delete them.  

Controller Version - AppDynamics Controller build 21.4.1-1259

Thanks for considering the request to add feature for deleting SEPs using API.

**Comment by svrnm** [comment]
fixed with the latest release, please try it out and let me know if it works:-)
