### ISSUE TITLE
How to search metric data within the customer time range?

### ISSUE THREAD

**Issue by nch0517** [Appdynamics/api-commandline-tool#36]
Hi, the tool is good and it's helping me a lot to retrieve data from the metric in appd using "metric get". However, may i know how to retrieve data from specific time range? thanks!

**Comment by svrnm** [comment]
hi @nch0517, `metric get` accepts a few more parameters, which I forgot to list in the help:
```
-s starttime
-e endtime
-d duration in minutes
-t type
-r rollup
```

I hope that helps.

**Comment by nch0517** [comment]
Thanks for your help and may i know the time range format? is it Unix Epoch Time?

**Comment by nch0517** [comment]
i have tested and it should be epoch time, thanks!
