### ISSUE TITLE
Event create doesn't work

### ISSUE THREAD

**Issue by jeromeguillaume** [Appdynamics/api-commandline-tool#4]
When I execute the command below, the controller sends an error message "Event severity is not specified...The request sent by the client was syntactically incorrect"

`/home/ubuntu/api-commandline-tool/act.sh -H http://172.17.0.1:8090 -C admin@customer1:appdynamics event create -a 5 -s "Test" -l "INFO" -e "APPLICATION_DEPLOYMENT" "Create application deployment"`

**Comment by svrnm** [comment]
The last commit should fix this issue, what also should work is calling the comment explicitly: 

```shell
/home/ubuntu/api-commandline-tool/act.sh -H http://172.17.0.1:8090 -C admin@customer1:appdynamics event create -a 5 -s "Test" -l "INFO" -e "APPLICATION_DEPLOYMENT" -c "Create application deployment"
```
