### ISSUE TITLE
Ability to export Custom Metrics

### ISSUE THREAD

**Issue by asafkiv** [Appdynamics/api-commandline-tool#41]
Hi.
I wanted to have the option to export and import my custom analytics queries. 
currently the only supported parameter is to create a custom analytics metric. Is there a workaround for it?

**Comment by svrnm** [comment]
Hi,

I just added a sub-command to retrieve all custom analytics metrics in a list format. So you can now run `act.sh analyticsmetric list`, although this is not a real import/export mechanism, but there is no API for that exposed. What you probably need to do is create a script wrapper around that.

Hope that helps

**Comment by asafkiv** [comment]
Thanks a lot.
Will check it shortly and respond.

**Comment by asafkiv** [comment]
Amazing! Works.
