### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by MeetupAcct** [Appdynamics/api-commandline-tool#5]
Provided the correct controller endpoint, uname/pwd for logging in via regular controller UI, but then when I try any commands, I get this below - what creates the "cookie.txt"?

jdice-mac:api-commandline-tool jeff.dice$ ./act.sh dashboard list
grep: /Users/jeff.dice/.appdynamics/act/cookie.txt: No such file or directory
Controller Login Error! Please check hostname and credentials

**Comment by michaelenglert** [comment]
can't reproduce the issue with the latest controller version. please follow the steps similar to the screenshot below
![image](https://user-images.githubusercontent.com/7372469/50819201-a9828180-1329-11e9-85da-c36ae8ef4bf2.png)
