### ISSUE TITLE
bash/echo is printing escaped response

### ISSUE THREAD

**Issue by jscottnz** [Appdynamics/api-commandline-tool#6]
Hi there.

I've stumbled across an issue with json responses that contain escaped strings, whereby echo is interpreting the escape, rather than just printing the response.

for example:
when you call the restui for the transaction rules `/controller/restui/transactionConfigProto/getRules/32` on a new application with the default transaction rules such as "Python Static Content Filter" which contain the regex `"robots.txt|.*\\.(js|css|png|gif|jpg|jpeg|ico)$"` the curl response is correct, but echo prints it as `"robots.txt|.*\.(js|css|png|gif|jpg|jpeg|ico)$"` which is not valid json, ie it does not parse with jq

poking around the web says that this might be bash/echo implementation specific. I've tested this on my local osx and also in a amazon 2 linux.

Any hints muchly appreciated...

Also.. on the off chance - how do you all go about 'cloning' an appd application into another application on the same controller. ie. we have a 'test' controller and the company has many test environments all pointing to their own appd applications. this makes a nightmare for configuration management of bts, analytics metrics when trying to keep it all in sync.

Thanks heaps

**Comment by michaelenglert** [comment]
should be fixed now by latest [commit](https://github.com/Appdynamics/api-commandline-tool/commit/67a9e4c4ce14418ae7fe723d3ac04097a840ccd0) 
replaced echo with printf for command result outputs. Should be more reliable that way

**Comment by michaelenglert** [comment]
@jscottnz can you check if this solves the issue you had?

**Comment by jscottnz** [comment]
LGTM!

Thanks
