### ISSUE TITLE
Postman Import from Link failing with Error while importing: format not recognized

### ISSUE THREAD

**Issue by reach2prakash** [Appdynamics/api-commandline-tool#9]
Postman Import from Link failing with Error while importing: format not recognized
Link: https://raw.githubusercontent.com/Appdynamics/api-commandline-tool/master/postman-collection.json

Import failed.
Postman-win64-7.2.2-Setup.exe

**Comment by svrnm** [comment]
@reach2prakash thanks for calling this out! This was a stupid bug in the description of one of the commands that broke the whole JSON... can you retry?

**Comment by reach2prakash** [comment]
Hi, sure, I will try it tomorrow and get back .thank you for reverting and
help. Cheers

**Comment by reach2prakash** [comment]
yeah, it works now. thanks - cheers.
